### PR TITLE
Safe cloning user object for further serialization

### PR DESCRIPTION
**Pull request by chrisbujok**
Hello,

I tried to use this module with my feathers app and `feathers-sequelize` Users service, but functions `sanitizeUserForClient` and `sanitizeUserForNotifier` cause error:

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (/***/node_modules/express/lib/response.js:1064:12)
    at ServerResponse.json (/***/node_modules/express/lib/response.js:243:14)
    at Object.applicationJson [as application/json] (/***/node_modules/feathers-rest/lib/index.js:27:11)
    at ServerResponse.res.format (/***/node_modules/express/lib/response.js:628:13)
    at formatter (/***/node_modules/feathers-rest/lib/index.js:25:7)
    at Layer.handle [as handle_request] (/***/node_modules/express/lib/router/layer.js:95:5)
    at next (/***/node_modules/express/lib/router/route.js:131:13)
    at Object.callback (/***/node_modules/feathers-rest/lib/wrappers.js:87:14)
    at callbackWrapper (/***/node_modules/rubberduck/lib/rubberduck.js:50:20)
    at /***/node_modules/feathers/lib/mixins/promise.js:35:14
```

I think this is because `Object.assign()` does not copy values like custom `toJSON` method, which is used e.g. in Sequelize model objects and is necessary for proper object serialization.

I came up with idea of checking for existence of custom `toJSON` method in user object and then using it's result as a source for new user object. It happens only when `JSON.stringify()` throws error, so in my opinion - only when necessary.

The caveat is that after object sanitization, sequelize methods inside model object will not be accessible, but this is the same situation as current.

Please let me know what do you think.

### CODE REVIEW

**Comment by eddyystop** [comment]
Thanks for the catch.
I somehow missed this PR for 3 days. Sorry.

MongoDB has a similar issue. It uses a `.toObject` function instead of `.toJSON`.
Perhaps `cloneObject` is more descriptive name that `cloneUserObject`.

Would you mind making these 2 changes to the PR?

**Comment by chrisbujok** [comment]
Sorry, I just found some time to fix this.
I've added support for `toObject` but `toJSON` has precedence over it.

**Comment by eddyystop** [comment]
+1 Thanks

**Comment by eddyystop** [comment]
Pushed with 0.1.6

**Pull request merged**
