### PR TITLE
added `sanitizeUserForClient` to options

### LINKED ISSUE #46: option to customize `sanitizeUserForClient` function
### Steps to reproduce
I have a use case where sensitive data is stored on the user object, which has sanitation hooks on the user service when the provider is remote.
These sanitation hooks are circumvented by the authManagement service (it being a server-side call) leading to the entire user object being returned, and subsequently sent down to the client. In these cases the client may be completely anonymous.

### Expected behavior
Should be able to customize the sanitation of the user returned from the authManagement service.

### Actual behavior
User contains all data, save what the authManagement service deems appropriate to remove.

### System configuration
N/A

I am happy to implement this an send a PR across, just let me know.

It might be beneficial to also allow customized functions for other helpers.

### PR DESCRIPTION
**Pull request by markacola**
### Summary

This allows customization of the `sanitizeUserForClient` helper function, fixes #46.

### Other Information

This could be further extended to allow customization of other helper functions. Happy to add these to the PR, just let me know.

### CODE REVIEW

**Comment by eddyystop** [comment]
Could you add tests for this? Thanks.

**Comment by markacola** [comment]
Is this tests sufficient? I believe I have implemented it correctly.

**Comment by eddyystop** [comment]
As far as I can tell, this code does not default to the existing `sanitizeUserForClient` routine. The user is required to pass a new sanitization option, which is a breaking change.

**Comment by markacola** [comment]
The `sanitizeUserForClient` helper is imported into `src/service.js` and set as the `sanitizeUserForClient` in the `optionsDefault`.
I have modified everywhere `sanitizeUserForClient` is used to pull it out of options instead of the helpers import.

**Comment by eddyystop** [comment]
Yup. I missed that.

Thanks for the PR!

**Pull request merged**
